name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'set repo prefix'
        required: true
        default: 'service'
        type: choice
        options:
          - example
          - service
      name:
        description: 'set repo name'
        required: true
        default: 'github-actions'
        type: string
jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token
      - name: create-repo
        id: create-repo
        run: |
          gh repo create taewa-study/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme
      - name: slack
        if: always()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "Danny Torrence left a 1 star review for your property.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Danny Torrence left the following review for your property:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://example.com|*Overlook Hotel*> :star: \n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/d3/72/5c/d3725c8f-c642-5d69-1904-aa36e4297885/source/256x256bb.jpg",
                    "alt_text": "Haunted hotel image"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Average Rating*: 1.0"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "create repo result: ${{ steps.create-repo.outcome }} ${{ inputs.prefix }}-${{ inputs.name }} 실패입니다"
                  }
                }
              ]
            }
